name: validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Select Node Version
        uses: svierk/get-node-version@main
      - name: Install Dependencies
        run: npm ci
      - name: Check Prettier
        run: npm run prettier
      - name: Check ESLint
        run: npm run lint:sonar
      - name: LWC Unit Tests
        run: npm run test:unit:coverage
      - name: Install SF CLI
        uses: svierk/sfdx-cli-setup@main
        with:
          plugins: "['@salesforce/sfdx-scanner@latest']"
      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v1
        with:
          run-command: run
          run-arguments: --normalize-severity --target . --outfile results.html
          results-artifact-name: salesforce-code-analyzer-results
      - name: Salesforce Org Login
        uses: svierk/sfdx-login@main
        with:
          client-id: ${{ secrets.SFDX_CONSUMER_KEY }}
          jwt-secret-key: ${{ secrets.SFDX_JWT_SECRET_KEY }}
          username: ${{ secrets.SFDX_USERNAME }}
      - name: Deploy Metadata
        run: sf project deploy start
      - name: Apex Unit Tests
        run: sf apex run test --test-level=RunLocalTests --code-coverage --result-format=human -w 30 -d ./tests/apex --detailed-coverage
